config/routes.rb
Rails.application.routes.draw do
  resources :notebooks do
    resources :pages do
      resources :paragraphs
      resources :image_elements
      resources :checklists do
        resources :checklist_items
      end
    end
  end
  devise_for :users
  root to: "notebooks#index"
end

app/models/notebook.rb
class Notebook < ApplicationRecord
  belongs_to :user
  has_many :pages, dependent: :destroy

  def get_next_page_position
    if pages.none? { |page| page.persisted? }
      1
    else
      pages.order(position: :asc).last.position + 1
    end
  end
  
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_notebook, only: [:show, :edit, :update, :destroy]
  before_action :set_base_breadcrumbs, only: [:show, :new, :edit]

  # GET /notebooks
  # GET /notebooks.json
  def index
    @notebooks = current_user.notebooks
    add_breadcrumb('Notebooks')
  end

  # GET /notebooks/1
  # GET /notebooks/1.json
  def show
    add_breadcrumb(@notebook.title)
  end

  # GET /notebooks/new
  def new
    @notebook = Notebook.new
    add_breadcrumb('New')
  end

  # GET /notebooks/1/edit
  def edit
    add_breadcrumb(@notebook.title, notebook_path(@notebook))
    add_breadcrumb('Edit')
  end

  # POST /notebooks
  # POST /notebooks.json
  def create
    @notebook = current_user.notebooks.build(notebook_params)

    respond_to do |format|
      if @notebook.save
        format.html { redirect_to @notebook, notice: 'Notebook was successfully created.' }
        format.json { render :show, status: :created, location: @notebook }
      else
        format.html { render :new }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notebooks/1
  # PATCH/PUT /notebooks/1.json
  def update
    respond_to do |format|
      if @notebook.update(notebook_params)
        format.html { redirect_to @notebook, notice: 'Notebook was successfully updated.' }
        format.json { render :show, status: :ok, location: @notebook }
      else
        format.html { render :edit }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notebooks/1
  # DELETE /notebooks/1.json
  def destroy
    @notebook.destroy
    respond_to do |format|
      format.html { redirect_to notebooks_url, notice: 'Notebook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notebook
      @notebook = current_user.notebooks.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notebook_params
      params.require(:notebook).permit(:title)
    end

    def set_base_breadcrumbs
      add_breadcrumb('Notebooks', notebooks_path)
    end
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/views/notebooks/_form.html.erb
<%= form_with(model: notebook, local: true) do |form| %>
  <% if notebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notebook.errors.count, "error") %> prohibited this notebook from being saved:</h2>

      <ul>
        <% notebook.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', notebooks_path, class: 'btn btn-secondary ml-1' %>
  </div>
<% end %>

app/views/notebooks/edit.html.erb
<h3>
  Editing Notebook
  <%= link_to 'View', @notebook, class: 'btn btn-outline-primary' %>  
</h3>

<%= render 'form', notebook: @notebook %>

app/views/notebooks/index.html.erb
<p id="notice"><%= notice %></p>

<h3 class="d-flex justify-content-between mb-4">
  <span>Notebooks</span>
  <%= link_to 'New Notebook', new_notebook_path, class: 'btn btn-primary' %>
</h3>

<div class="row">
  <% @notebooks.each do |notebook| %>
    <div class="col-md-4">
      <div class="card notebook-card mb-3">
        <div class="card-body">
          <h5 class="card-title d-flex justify-content-between">
            <%= link_to notebook.title, notebook %>
            <div class="dropdown">
              <button class="btn btn-light" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-ellipsis-h"></i>
              </button>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <%= link_to 'Edit', edit_notebook_path(notebook), class: 'dropdown-item'%>
                <%= link_to 'Delete', notebook, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item' %>
              </div>
            </div>
          </h5>
          <div class="stats mb-4">
            <p class="page-count">
              <%= pluralize(notebook.pages.count, 'page') %>
            </p>
            <p class="started">
              Started <%= time_ago_in_words(notebook.created_at) %> ago
            </p>
          </div>
          <%= link_to "View", notebook, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/notebooks/new.html.erb
<h3>New Notebook</h3>

<%= render 'form', notebook: @notebook %>

app/views/notebooks/show.html.erb
<p id="notice"><%= notice %></p>

<h3 class="mb-4">
  <%= @notebook.title %>
  <%= link_to 'Edit', edit_notebook_path(@notebook), class: 'btn btn-outline-primary' %>
</h3>

<h5 class="d-flex justify-content-between">
  <span>Pages</span>
  <%= link_to 'New Page', new_notebook_page_path(@notebook), class: 'btn btn-primary' %>
</h5>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @notebook.pages.each do |page| %>
      <tr>
        <td><%= page.position %></td>
        <td><%= link_to page.title, notebook_page_path(@notebook, page) %></td>
        <td><%= link_to 'Edit', edit_notebook_page_path(@notebook, page) %></td>
        <td><%= link_to 'Destroy', notebook_page_path(@notebook, page), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>