config/routes.rb
Rails.application.routes.draw do
  resources :notebooks do
    resources :pages do
      resources :paragraphs
      resources :image_elements
      resources :checklists do
        resources :checklist_items
      end
    end
  end
  devise_for :users
  root to: "notebooks#index"
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  belongs_to :page
  has_many :checklist_items

  def new_item
    checklist_items.build
  end

  def percent_complete
    return 0 if total_items == 0
    ((checklist_items.select(&:complete?).count.to_f / total_items) * 100).round
  end

  def percent_in_progress
    return 0 if total_items == 0
    ((checklist_items.select(&:in_progress?).count.to_f / total_items) * 100).round
  end
  
  def total_items
    @total_items ||= checklist_items.count
  end
  
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_checklist, only: [:show, :edit, :update, :destroy]

  # GET /checklists
  def index
    @checklists = Checklist.all
  end

  # GET /checklists/1
  def show
  end

  # GET /checklists/new
  def new
    @checklist = Checklist.new
  end

  # GET /checklists/1/edit
  def edit
  end

  # POST /checklists
  def create
    notebook = current_user.notebooks.find(params[:notebook_id])
    page = notebook.pages.find(params[:page_id])
    checklist = page.checklists.create
    redirect_to notebook_page_path(notebook, page)
  end

  # PATCH/PUT /checklists/1
  def update
    notebook = current_user.notebooks.find(params[:notebook_id])
    page = notebook.pages.find(params[:page_id])
    checklist = page.checklists.find(params[:id])
    checklist.update(checklist_params)
    redirect_to notebook_page_path(notebook, page)
  end

  # DELETE /checklists/1
  def destroy
    @checklist.destroy
    redirect_to checklists_url, notice: 'Checklist was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checklist
      @checklist = Checklist.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def checklist_params
      params.require(:checklist).permit(:title)
    end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/views/checklists/_checklist.html.erb
<% page = checklist.page %>
<% notebook = page.notebook %>

<% if checklist.persisted? %>
      <div class="p-4" id="checklist-<%= checklist.id %>">
        <div class="text-content mb-2 p-2">
          <% if checklist.title.present? %>
            <h5 class="m-0"><%= checklist.title %></h5>
          <% else %>
            <h5 class="m-0 text-muted">Click to add title</h5>
          <% end %>
        </div>
        <div class="form-content mb-2 d-none">
          <%= form_with(model: [notebook, page, checklist]) do |form| %>
            <label>Checklist title</label>
            <%= form.text_field :title, class: 'form-control' %>
            <div class="buttons mt-3">
              <%= form.submit "Save", class: 'btn btn-primary' %>
              <a href="#" class="cancel btn btn-light">Cancel</a>
            </div>
          <% end %>
        </div>
        <div class="checklist-item-form">
          <%= form_with(model: [notebook, page, checklist, checklist.new_item]) do |form| %>
            <div class="input-group">
              <%= form.text_field :title, class: 'form-control', placeholder: "Add a new checklist item" %>
              <div class="input-group-append">
                <%= form.submit "Save", class: 'btn btn-dark' %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="checklist-items mt-3">
          <div class="progress mb-3">
            <% percent_complete = checklist.percent_complete %>
            <% percent_in_progress = checklist.percent_in_progress %>
            <div class="progress-bar bg-dark" role="progressbar" style="width: <%= percent_complete %>%" aria-valuenow="<%= percent_complete %>" aria-valuemin="0" aria-valuemax="100"></div>
            <div class="progress-bar bg-primary" role="progressbar" style="width: <%= percent_in_progress %>%" aria-valuenow="<%= percent_in_progress %>" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <ul class="list-group">
            <% checklist.checklist_items.each do |checklist_item| %>
              <% if checklist_item.persisted? %>
                <li class='list-group-item d-flex justify-content-between'>
                  <span><%= checklist_item.title %></span>
                  <div>
                    <div class="dropdown float-left mr-4">
                      <button class="btn btn-sm mr-1 btn-outline-<%= checklist_item.color_class %> dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= checklist_item.readable_status %>
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <% ChecklistItem::STATUS_OPTIONS.each do |status| %>
                          <a href="#" class="dropdown-item" 
                          data-reflex="click->ChecklistItemReflex#change_status" 
                          data-id="<%= checklist_item.id %>" 
                          data-status="<%= status[1] %>">
                            <%= status[0] %>
                          </a>
                        <% end %>
                      </div>
                    </div>
                    <%= link_to notebook_page_checklist_checklist_item_path(notebook, page, checklist, checklist_item), method: :delete, data: { confirm: "Are you sure?" }  do %>
                      <i class="fa fa-times text-secondary"></i>
                    <% end %>
                  </div>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>